version: '3.3'

services:
  app:
    image: python:latest
    tty: true
    stdin_open: true
    container_name: login-backend
    working_dir: /app
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./:/app
  db:
    image: mysql:8.0.23
    container_name: login-backend-db
    ports:
      - "3000:3006"
    environment:
      - MYSQL_ROOT_PASSWORD=password